-- Burn Test QC - Supabase/PostgreSQL
-- Run this in Supabase Dashboard > SQL Editor.
-- The Node backend uses the service-role key, so application requests do not
-- need public table policies.

create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint customers_name_unique unique (name)
);

create unique index if not exists customers_name_lower_unique
  on public.customers (lower(name));

create table if not exists public.purchase_orders (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on delete restrict,
  po_number text not null,
  created_at timestamptz not null default now(),
  constraint purchase_orders_customer_po_unique unique (customer_id, po_number)
);

create index if not exists idx_po_customer on public.purchase_orders(customer_id);
create index if not exists idx_po_number on public.purchase_orders(po_number);

create table if not exists public.burn_tests (
  id bigint generated by default as identity primary key,
  purchase_order_id bigint not null references public.purchase_orders(id) on delete restrict,
  product_code text not null,
  diameter_mm double precision,
  height_mm double precision,
  fragrance text,
  color text,
  wick text,
  temperature_c double precision,
  test_date date not null,
  test_time text,
  start_datetime text,
  end_datetime text,
  total_burn_time text,
  tester text,
  approver text,
  result text not null default 'PENDING'
    constraint burn_tests_result_check check (result in ('PASS','FAIL','PENDING')),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_test_po on public.burn_tests(purchase_order_id);
create index if not exists idx_test_product on public.burn_tests(product_code);
create index if not exists idx_test_date on public.burn_tests(test_date);
create index if not exists idx_test_result on public.burn_tests(result);

create table if not exists public.burn_test_photos (
  id bigint generated by default as identity primary key,
  burn_test_id bigint not null references public.burn_tests(id) on delete cascade,
  slot integer not null constraint burn_test_photos_slot_check check (slot between 1 and 5),
  file_name text not null,
  file_url text not null,
  original_name text,
  mime_type text,
  file_size bigint,
  created_at timestamptz not null default now(),
  constraint burn_test_photos_test_slot_unique unique (burn_test_id, slot)
);

create index if not exists idx_photo_test on public.burn_test_photos(burn_test_id);

-- Public read bucket: the backend uploads with service_role, while the
-- browser can display image URLs without exposing any Supabase key.
insert into storage.buckets (id, name, public)
values ('burn-test-photos', 'burn-test-photos', true)
on conflict (id) do update set public = true;

-- Keep application tables protected from anonymous direct access.
alter table public.customers enable row level security;
alter table public.purchase_orders enable row level security;
alter table public.burn_tests enable row level security;
alter table public.burn_test_photos enable row level security;


-- Helper used once by scripts/migrate-to-supabase.js after explicit legacy IDs
-- are imported. Safe to run repeatedly.
create or replace function public.sync_burntest_identity_sequences()
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  perform setval(
    pg_get_serial_sequence('public.customers', 'id'),
    greatest(coalesce((select max(id) from public.customers), 1)),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.purchase_orders', 'id'),
    greatest(coalesce((select max(id) from public.purchase_orders), 1)),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.burn_tests', 'id'),
    greatest(coalesce((select max(id) from public.burn_tests), 1)),
    true
  );
  perform setval(
    pg_get_serial_sequence('public.burn_test_photos', 'id'),
    greatest(coalesce((select max(id) from public.burn_test_photos), 1)),
    true
  );
end;
$$;

revoke execute on function public.sync_burntest_identity_sequences() from public;
grant execute on function public.sync_burntest_identity_sequences() to service_role;
